spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/gabrieloest/microservicesNetflixOSS
          search-paths:
            - "ms-config-properties/{application}/{profile}"
            - "ms-config-properties/global/{profile}"